# Generated by Django 5.1.4 on 2025-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='board_of_education',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('state_board', 'State Board')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='class_level',
            field=models.CharField(blank=True, choices=[('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
