# Generated by Django 5.1.4 on 2025-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_agreed_to_terms_user_board_of_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='board_of_education',
        ),
        migrations.AlterField(
            model_name='user',
            name='class_level',
            field=models.CharField(blank=True, choices=[('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
