# Generated by Django 5.1.4 on 2025-06-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_board_of_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
