# Generated by Django 5.2.2 on 2025-08-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_class_level_remove_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth'), ('facebook', 'Facebook OAuth')], default='email', help_text='Method used for initial registration', max_length=20),
        ),
    ]
