# Generated by Django 5.2.2 on 2025-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_auth_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth')], default='email', help_text='Method used for initial registration', max_length=20),
        ),
    ]
