# Generated by Django 5.1.4 on 2025-10-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False, help_text='Whether user has seen the onboarding modal'),
        ),
    ]
