# Generated by Django 5.1.4 on 2026-05-31 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_has_seen_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(choices=[('courses', 'Courses'), ('codevisualizer', 'Code Visualizer'), ('scrib', 'Scrib'), ('main', 'Main Website')], default='main', help_text='Which product the user originally signed up from', max_length=50),
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('courses', 'Courses'), ('codevisualizer', 'Code Visualizer'), ('scrib', 'Scrib')], max_length=50)),
                ('first_used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_used_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
