# Generated by Django 5.1.4 on 2026-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_signup_source_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_cohort',
            field=models.CharField(blank=True, help_text='Scrib marketing cohort active when this user first signed up (preview | free_credit | null if pre-dates cohort tracking)', max_length=20, null=True),
        ),
    ]
