# Generated by Django 5.2.7 on 2026-07-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_add_signup_cohort_to_user'),
        ('scrib', '0017_influencer_influencercommission_influencerreferral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by_influencer',
            field=models.ForeignKey(blank=True, help_text='The influencer who referred this user (set once at signup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='scrib.influencer'),
        ),
    ]
