version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/courses-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/company-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/codevisualizer-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
