#!/usr/bin/env python3
"""
Test the new smart course naming system
Frontend generates smart names, backend uses them as-is
"""

import requests
import json

def test_smart_course_naming():
    """Test the new smart naming system"""
    url = "http://localhost:8000/api/courses/pro-learning-direct/save/"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer test-token"
    }
    
    print("🧪 Testing Smart Course Naming System...")
    
    # Test 1: Single topic course (frontend should generate "AI Course: Topic Name")
    single_topic_data = {
        "course_id": "single-topic-test",
        "title": "AI Course: Machine Learning Basics",  # Smart name generated by frontend
        "topics": {
            "Machine Learning Basics": {
                "content": {
                    "reading": "Machine learning is a subset of AI that focuses on algorithms that can learn from data.",
                    "summary": "ML enables computers to learn from data without explicit programming.",
                    "videos": [{"title": "ML Intro", "url": "https://example.com/ml1"}],
                    "quiz": [{"question": "What is ML?", "options": ["AI subset", "Programming", "Data", "Algorithm"], "correct": 0}],
                    "resources": [{"title": "ML Guide", "url": "https://example.com/ml-guide"}]
                }
            }
        }
    }
    
    # Test 2: Two topics course (frontend should generate "AI Course: Topic1 + Topic2")  
    two_topics_data = {
        "course_id": "two-topics-test",
        "title": "AI Course: Python Basics + Data Structures",  # Smart name for 2 topics
        "topics": {
            "Python Basics": {
                "content": {
                    "reading": "Python is a high-level programming language known for its simplicity and readability.",
                    "summary": "Python is an easy-to-learn programming language with clear syntax.",
                    "videos": [{"title": "Python Intro", "url": "https://example.com/py1"}],
                    "quiz": [{"question": "What is Python?", "options": ["Language", "Snake", "Tool", "Framework"], "correct": 0}],
                    "resources": [{"title": "Python Docs", "url": "https://python.org"}]
                }
            },
            "Data Structures": {
                "content": {
                    "reading": "Data structures are ways of organizing and storing data to enable efficient access and modification.",
                    "summary": "Data structures organize data for efficient access and operations.",
                    "videos": [{"title": "Data Structures 101", "url": "https://example.com/ds1"}],
                    "quiz": [{"question": "What are data structures?", "options": ["Data organization", "Code", "Variables", "Functions"], "correct": 0}],
                    "resources": [{"title": "DS Guide", "url": "https://example.com/ds-guide"}]
                }
            }
        }
    }
    
    # Test 3: Many topics course (frontend should generate "AI Course: Topic1 + Topic2 + Topic3 + ...")
    many_topics_data = {
        "course_id": "many-topics-test", 
        "title": "AI Course: HTML + CSS + JavaScript + React + ...",  # Smart name for many topics
        "topics": {
            "HTML": {"content": {"reading": "HTML structures web content.", "summary": "HTML is markup language.", "videos": [], "quiz": [], "resources": []}},
            "CSS": {"content": {"reading": "CSS styles web pages.", "summary": "CSS handles styling.", "videos": [], "quiz": [], "resources": []}},
            "JavaScript": {"content": {"reading": "JavaScript adds interactivity.", "summary": "JS enables dynamic behavior.", "videos": [], "quiz": [], "resources": []}},
            "React": {"content": {"reading": "React builds user interfaces.", "summary": "React creates UIs.", "videos": [], "quiz": [], "resources": []}},
            "Node.js": {"content": {"reading": "Node.js runs JS on servers.", "summary": "Node enables server-side JS.", "videos": [], "quiz": [], "resources": []}}
        }
    }
    
    test_cases = [
        ("Single Topic", single_topic_data, "AI Course: Machine Learning Basics"),
        ("Two Topics", two_topics_data, "AI Course: Python Basics + Data Structures"), 
        ("Many Topics", many_topics_data, "AI Course: HTML + CSS + JavaScript + React + ...")
    ]
    
    for test_name, test_data, expected_name in test_cases:
        print(f"\n📝 Test: {test_name}")
        print(f"   Expected: '{expected_name}'")
        
        try:
            response = requests.post(url, headers=headers, json=test_data, timeout=30)
            if response.status_code in [200, 201]:
                result = response.json()
                actual_name = result['course']['course_name']
                print(f"   Actual:   '{actual_name}'")
                if actual_name == expected_name:
                    print(f"   ✅ PASS: Names match!")
                else:
                    print(f"   ❌ FAIL: Names don't match")
            elif response.status_code == 409:
                print(f"   ⚠️  Course already exists (409) - this is expected if running multiple times")
            else:
                print(f"   ❌ Failed: Status {response.status_code}, Response: {response.text}")
        except Exception as e:
            print(f"   ❌ Error: {e}")

if __name__ == "__main__":
    test_smart_course_naming()
