#!/usr/bin/env python
"""
Test script for the new AI Course system
This tests the create_or_get_ai_course endpoint and course-topic relationships
"""

import os
import sys
import django
import json
import requests

# Add the backend directory to Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from courses.models import AILearningCourse, AITopicContent
from django.contrib.auth import get_user_model

User = get_user_model()

def test_ai_course_creation():
    """Test creating AI courses and linking topics"""
    print("=== Testing AI Course System ===\n")
    
    # Get or create a test user
    user, created = User.objects.get_or_create(
        email='testuser@example.com',
        defaults={'full_name': 'Test User'}
    )
    if created:
        print("✅ Created test user")
    else:
        print("✅ Using existing test user")
    
    # Test data for AI course
    course_data = {
        'course_identifier': 'ai-python-basics',
        'course_title': 'AI-Generated Python Basics',
        'description': 'Complete guide to Python fundamentals generated by AI',
        'topics_list': ['Variables and Data Types', 'Control Structures', 'Functions', 'Classes and Objects'],
        'user': user
    }
    
    # Create or get AI course
    course, created = AILearningCourse.objects.get_or_create(
        course_identifier=course_data['course_identifier'],
        user=course_data['user'],
        defaults={
            'course_title': course_data['course_title'],
            'description': course_data['description'],
            'topics_list': course_data['topics_list']
        }
    )
    
    if created:
        print(f"✅ Created new AI course: {course.course_title}")
    else:
        print(f"✅ Retrieved existing AI course: {course.course_title}")
    
    print(f"   Course ID: {course.id}")
    print(f"   Course URL: {course.get_course_url()}")
    print(f"   Topics: {course.topics_list}")
    
    # Create some topic content linked to this course
    topics_data = [
        {
            'topic_name': 'Variables and Data Types',
            'reading': 'In Python, variables are used to store data values...',
            'summary': 'Variables store data, Python has dynamic typing',
            'videos': ['https://youtube.com/watch?v=example1'],
            'resources': ['Python official docs on variables']
        },
        {
            'topic_name': 'Control Structures',
            'reading': 'Control structures determine the flow of program execution...',
            'summary': 'if/else, loops control program flow',
            'videos': ['https://youtube.com/watch?v=example2'],
            'resources': ['Python control flow guide']
        }
    ]
    
    created_topics = []
    for topic_data in topics_data:
        topic, created = AITopicContent.objects.get_or_create(
            topic_name=topic_data['topic_name'],
            ai_course=course,
            user=user,
            defaults={
                'reading': topic_data['reading'],
                'summary': topic_data['summary'],
                'videos': topic_data['videos'],
                'resources': topic_data['resources']
            }
        )
        created_topics.append(topic)
        
        if created:
            print(f"✅ Created topic: {topic.topic_name}")
        else:
            print(f"✅ Retrieved existing topic: {topic.topic_name}")
    
    # Test retrieving course with topics
    print(f"\n=== Course with Topics ===")
    course_with_topics = AILearningCourse.objects.prefetch_related('topic_contents').get(id=course.id)
    print(f"Course: {course_with_topics.course_title}")
    print(f"Topics count: {course_with_topics.topic_contents.count()}")
    
    for topic in course_with_topics.topic_contents.all():
        print(f"  - {topic.topic_name}")
        print(f"    Created: {topic.created_at}")
        print(f"    Has reading: {bool(topic.reading)}")
        print(f"    Has summary: {bool(topic.summary)}")
    
    print(f"\n=== Test Completed Successfully ===")
    print(f"✅ AI Course system is working correctly!")
    print(f"✅ Course-topic relationships established")
    print(f"✅ Ready for frontend integration")

if __name__ == '__main__':
    test_ai_course_creation()
