# Generated by Django 5.1.4 on 2026-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewnote',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previewnote',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
