# Generated by Django 5.1.4 on 2026-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0002_add_pdf_url_to_previewnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypack',
            name='s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
