# Generated by Django 5.1.4 on 2026-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0003_add_s3_key_to_study_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypack',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
