# Generated by Django 5.1.4 on 2026-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0004_fix_pdf_url_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypack',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True, unique=True),
        ),
    ]
