# Generated by Django 5.1.4 on 2026-06-19 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0006_studypack_pages_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('payment', 'Payment'), ('generation', 'Generation'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('promo', 'Promo Code')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('credits_to_add', models.PositiveIntegerField(default=5)),
                ('campaign_name', models.CharField(max_length=100)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_added', models.PositiveIntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='scrib.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='scrib_promo_code_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['campaign_name'], name='scrib_promo_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'expires_at'], name='scrib_promo_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['promo_code', 'user'], name='scrib_rdem_code_user_idx'),
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['user', 'redeemed_at'], name='scrib_rdem_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocoderedemption',
            unique_together={('promo_code', 'user')},
        ),
    ]
