# Generated by Django 5.1.4 on 2026-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0007_add_promocode_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScribConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('preview', 'Preview Modal (Cohort A)'), ('free_credit', 'Free Credit Modal (Cohort B)')], default='preview', max_length=20)),
                ('give_free_credit_on_signup', models.BooleanField(default=False, help_text='When True and cohort is free_credit, grant 1 free credit on OTP signup verification.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scrib Config',
                'verbose_name_plural': 'Scrib Config',
            },
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('payment', 'Payment'), ('generation', 'Generation'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('promo', 'Promo Code'), ('signup_bonus', 'Signup Bonus')], max_length=20),
        ),
    ]
