# Generated by Django 5.1.4 on 2026-07-03 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0008_scrib_config_cohort_toggle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('preview', 'Cohort A — Preview Modal'), ('free_credit', 'Cohort B — Free Credit')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('switched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort Period',
                'verbose_name_plural': 'Cohort Periods',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['cohort'], name='scrib_cohort_period_cohort_idx'), models.Index(fields=['ended_at'], name='scrib_cohort_period_ended_idx')],
            },
        ),
    ]
