# Generated by Django 5.1.4 on 2026-07-16 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0012_apply_cohorts_last_3_days_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('payment', 'Payment'), ('generation', 'Generation'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('promo', 'Promo Code'), ('signup_bonus', 'Signup Bonus'), ('referral', 'Referral Reward')], max_length=20),
        ),
        migrations.CreateModel(
            name='NoteShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(db_index=True, help_text='8-char Base36 code used in the public share URL (e.g. SCR8F2KD)', max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_type', models.CharField(default='credits', help_text='credits in V1; change to cash in V2 without a migration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('study_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='scrib.studypack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedPackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField(help_text='Amount charged to the buyer in paise (1 INR = 100 paise)')),
                ('reward_amount', models.DecimalField(decimal_places=2, help_text='Units awarded to the sharer (credits in V1)', max_digits=10)),
                ('reward_type', models.CharField(default='credits', help_text='Type of reward: credits (V1) or cash (V2)', max_length=20)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When the buyer first opened the share landing page', null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('conversion_time', models.DurationField(blank=True, help_text='Time from first click to completed purchase (purchased_at - clicked_at)', null=True)),
                ('referrer', models.CharField(blank=True, help_text='HTTP Referer header or UTM source at click time', max_length=500)),
                ('device', models.CharField(blank=True, help_text='mobile | tablet | desktop — parsed from User-Agent', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser name parsed from User-Agent (e.g. Chrome, Safari)', max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code from CF-IPCountry header or blank', max_length=2)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_pack_purchases', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_purchases', to='scrib.payment')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='scrib.notesharelink')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notesharelink',
            index=models.Index(fields=['share_code'], name='scrib_sharelink_code_idx'),
        ),
        migrations.AddIndex(
            model_name='notesharelink',
            index=models.Index(fields=['owner', 'created_at'], name='scrib_sharelink_owner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notesharelink',
            unique_together={('study_pack', 'owner')},
        ),
        migrations.AddIndex(
            model_name='sharedpackpurchase',
            index=models.Index(fields=['buyer', 'purchased_at'], name='scrib_sharedpurch_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedpackpurchase',
            index=models.Index(fields=['share_link', 'purchased_at'], name='scrib_sharedpurch_link_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedpackpurchase',
            unique_together={('share_link', 'buyer')},
        ),
    ]
