# Generated by Django 5.1.4 on 2026-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0013_earn_while_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypack',
            name='s3_preview_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
