# Generated by Django 5.1.4 on 2026-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0014_studypack_s3_preview_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='credits',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='credits_to_add',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='promocoderedemption',
            name='credits_added',
            field=models.FloatField(),
        ),
    ]
