# Generated by Django 5.1.4 on 2026-07-19 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0015_alter_credittransaction_credits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpackpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pack_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedpackpurchase',
            name='share_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='scrib.notesharelink'),
        ),
    ]
