# Generated by Django 5.2.7 on 2026-07-22 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0016_alter_sharedpackpurchase_buyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dashboard_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveSmallIntegerField(help_text='1 for first payment, 2 for second payment')),
                ('payment_amount', models.PositiveIntegerField(help_text='Amount in paise')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amount', models.PositiveIntegerField(help_text='Commission in paise')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='scrib.influencer')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_commission', to='scrib.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='scrib.influencer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_referral_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visitor_id', models.UUIDField(db_index=True, help_text='Frontend generated UUID for deduplication')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='scrib.influencer')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['influencer', 'visitor_id', 'clicked_at'], name='scrib_influ_influen_31e9a9_idx')],
            },
        ),
    ]
