# Generated by Django 5.2.7 on 2026-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0017_influencer_influencercommission_influencerreferral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypack',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
