# Generated by Django 5.2.7 on 2026-08-14 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0018_studypack_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, default='interview', help_text="Top-level Library grouping, e.g. 'interview'.", max_length=40)),
                ('category', models.CharField(help_text="Subject shown above the title, e.g. 'Operating Systems'.", max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price_paise', models.PositiveIntegerField(default=9900, help_text='Price for this single pack, in paise (9900 = ₹99).')),
                ('theme', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('olive', 'Olive')], default='blue', max_length=20)),
                ('s3_key', models.CharField(blank=True, default='', help_text='S3 object key of the full PDF.', max_length=1024)),
                ('s3_free_key', models.CharField(blank=True, default='', help_text='S3 key of the extracted free-preview PDF. Regenerated when the source PDF changes.', max_length=1024)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('free_page_count', models.PositiveIntegerField(default=10, help_text='How many pages a user can read before paying.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='scrib_pack_section_idx'), models.Index(fields=['slug'], name='scrib_cpack_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('section', models.CharField(db_index=True, default='interview', max_length=40)),
                ('price_paise', models.PositiveIntegerField(default=39900, help_text='Bundle price in paise (39900 = ₹399).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packs', models.ManyToManyField(blank=True, related_name='bundles', to='scrib.contentpack')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Position within the pack, starting at 1.')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('topic', models.CharField(blank=True, default='', help_text="Sub-line shown on the quiz card, e.g. 'Processes & scheduling'.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='scrib.contentpack')),
            ],
            options={
                'verbose_name_plural': 'Pack quizzes',
                'ordering': ['pack', 'number'],
                'unique_together': {('pack', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PackQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scrib.packquiz')),
            ],
            options={
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='scrib.packbundle')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='scrib.contentpack')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_purchases', to='scrib.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='scrib_packpurch_user_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pack__isnull', False)), fields=('user', 'pack'), name='scrib_uniq_user_pack_purchase'), models.UniqueConstraint(condition=models.Q(('bundle__isnull', False)), fields=('user', 'bundle'), name='scrib_uniq_user_bundle_purchase')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='{question_id: chosen_index} as submitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scrib.packquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'quiz'], name='scrib_attempt_user_quiz_idx')],
            },
        ),
    ]
