# Generated by Django 5.2.7 on 2026-08-15 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0019_contentpack_packbundle_packquiz_packquizquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packpurchase',
            name='scrib_uniq_user_pack_purchase',
        ),
        migrations.RemoveConstraint(
            model_name='packpurchase',
            name='scrib_uniq_user_bundle_purchase',
        ),
        migrations.AddConstraint(
            model_name='packpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'pack'), name='scrib_uniq_user_pack_purchase'),
        ),
        migrations.AddConstraint(
            model_name='packpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'bundle'), name='scrib_uniq_user_bundle_purchase'),
        ),
    ]
