# Generated by Django 5.2.7 on 2026-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0020_remove_packpurchase_scrib_uniq_user_pack_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packbundle',
            name='covers_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many still-unowned packs this offer covers. 0 = the full offer over the packs picked below, shown only to users who own none of them. Set 2 to price the "already owns one, sell the other two" top-up — leave the pack list empty for those, the packs are whichever ones the buyer is missing.'),
        ),
    ]
