# Generated by Django 5.2.7 on 2026-08-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0021_packbundle_covers_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePackOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Master switch. Turn off to end the promo immediately.')),
                ('total_slots', models.PositiveIntegerField(default=150, help_text='How many users may claim a free pack in total.')),
                ('section', models.CharField(default='interview', help_text="Which Library section the offer covers, e.g. 'interview'.", max_length=40)),
                ('headline', models.CharField(default='Your first interview pack is free', help_text='Shown on the promo banner across the site.', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Pack Offer',
                'verbose_name_plural': 'Free Pack Offer',
            },
        ),
        migrations.CreateModel(
            name='FreePackClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_claims', to='scrib.contentpack')),
                ('purchase', models.ForeignKey(blank=True, help_text='The entitlement row this claim created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_claims', to='scrib.packpurchase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_pack_claim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='scrib_freeclaim_created_idx')],
            },
        ),
    ]
