# Generated by Django 5.2.7 on 2026-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrib', '0023_externalclientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percent of each qualifying payment paid to this influencer (first 2 payments only)', max_digits=5),
        ),
    ]
