# Generated by Django 5.1.4 on 2025-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcourse',
            name='class_level',
            field=models.CharField(choices=[('6th', 'Class 6'), ('7th', 'Class 7'), ('8th', 'Class 8'), ('9th', 'Class 9'), ('10th', 'Class 10'), ('11th', 'Class 11'), ('12th', 'Class 12')], max_length=10),
        ),
    ]
