# Generated by Django 5.1.4 on 2025-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_schoolcourse_class_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AILearningPlan',
        ),
    ]
