# Generated by Django 5.2.2 on 2025-07-28 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_schoolcourse_class_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITopicContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('topic_name', models.CharField(max_length=255)),
                ('reading', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('videos', models.JSONField(blank=True, default=list, help_text='List of video objects')),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of resource objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_topic_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Topic Content',
                'verbose_name_plural': 'AI Topic Contents',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course_title', 'topic_name')},
            },
        ),
    ]
