# Generated by Django 5.1.4 on 2025-07-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_aitopiccontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AILearningPlan',
        ),
    ]
