# Generated by Django 5.1.4 on 2025-07-30 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_ailearningplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProLearningCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pro Learning Course',
                'verbose_name_plural': 'Pro Learning Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProLearningTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('reading_material', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.prolearningcourse')),
            ],
            options={
                'verbose_name': 'Pro Learning Topic',
                'verbose_name_plural': 'Pro Learning Topics',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProLearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('link', 'External Link'), ('document', 'Document'), ('article', 'Article'), ('tool', 'Online Tool'), ('reference', 'Reference Material')], default='link', max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.prolearningtopic')),
            ],
            options={
                'verbose_name': 'Pro Learning Resource',
                'verbose_name_plural': 'Pro Learning Resources',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProLearningQuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='mcq', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.prolearningtopic')),
            ],
            options={
                'verbose_name': 'Pro Learning Quiz Question',
                'verbose_name_plural': 'Pro Learning Quiz Questions',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProLearningVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.prolearningtopic')),
            ],
            options={
                'verbose_name': 'Pro Learning Video',
                'verbose_name_plural': 'Pro Learning Videos',
                'ordering': ['topic', 'order'],
            },
        ),
    ]
