# Generated by Django 5.1.4 on 2025-07-30 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_ai_learning_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitopiccontent',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='List of project objects'),
        ),
        migrations.AddField(
            model_name='aitopiccontent',
            name='quiz',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz questions'),
        ),
        migrations.AddIndex(
            model_name='aitopiccontent',
            index=models.Index(fields=['user', 'course_title'], name='idx_user_course_title'),
        ),
        migrations.AddIndex(
            model_name='aitopiccontent',
            index=models.Index(fields=['created_at'], name='idx_ai_content_created_at'),
        ),
    ]
