# Generated by Django 5.1.4 on 2025-07-31 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_prolearningcourse_prolearningtopic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStartedPredefinedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('school', 'School Course'), ('engineering', 'Engineering Course')], max_length=20)),
                ('class_level', models.CharField(blank=True, choices=[('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], max_length=10, null=True)),
                ('board', models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state', 'State Board'), ('ib', 'International Baccalaureate')], max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('engineering_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='courses.engineeringcourse')),
                ('last_accessed_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_by_users', to='courses.lesson')),
                ('school_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='courses.schoolcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_predefined_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Started Predefined Course',
                'verbose_name_plural': 'User Started Predefined Courses',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'course_type'], name='idx_user_course_type'), models.Index(fields=['started_at'], name='idx_course_started_at'), models.Index(fields=['progress_percentage'], name='idx_course_progress')],
                'unique_together': {('user', 'engineering_course'), ('user', 'school_course')},
            },
        ),
    ]
