# Generated by Django 5.2.2 on 2025-08-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20250821_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolearningresource',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prolearningvideo',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
