# Generated by Django 5.2.6 on 2025-09-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursedraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDraft',
        ),
    ]
