# Generated by Copilot on 2025-10-12
from django.db import migrations, models
import uuid


def uuid_str():
    return str(uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_fix_lesson_section_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_id',
            field=models.CharField(max_length=36, default=uuid_str, unique=True, editable=False),
        ),
    ]
