# Generated by Django 5.2.2 on 2025-10-12 16:02

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_certification_certificate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certificate_id",
            field=models.CharField(
                default=courses.models.Certification.generate_uuid_str,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
    ]
