# Generated by Django 5.1.4 on 2025-10-27 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_fix_coursechapter_id_autoincrement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProLearningShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='courses.prolearningcourse', db_constraint=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pro Learning Share Link',
                'verbose_name_plural': 'Pro Learning Share Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course'], name='idx_share_course'), models.Index(fields=['created_by'], name='idx_share_creator'), models.Index(fields=['is_active'], name='idx_share_active')],
            },
        ),
    ]
