# Generated by Django 5.2.7 on 2025-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_add_lesson_updated_at_stateonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
