# Generated by Django 5.2.7 on 2025-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_coursechapter_is_deleted_coursesection_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
