# Generated by Django 5.2.7 on 2026-01-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursechapter_updated_at_coursesection_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringcourse',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube Curated'), ('original', 'EasyLearnova Original')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolcourse',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube Curated'), ('original', 'EasyLearnova Original')], default='youtube', max_length=20),
        ),
    ]
