# Generated by Django 5.2.7 on 2026-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_engineeringcourse_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringcourse',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube Curated'), ('original', 'EasyLearnova Original'), ('exam_ready', 'Exam Ready Series')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolcourse',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube Curated'), ('original', 'EasyLearnova Original'), ('exam_ready', 'Exam Ready Series')], default='youtube', max_length=20),
        ),
    ]
