# Generated by Django 5.1.4 on 2025-07-27 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when user subscribed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
