# Generated by Django 5.1.4 on 2025-07-27 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person providing feedback', max_length=100)),
                ('message', models.TextField(help_text='Feedback message content')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the feedback was submitted')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
